### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by roberttolton** [ignetic/ee-matrix-presets#2]
Add-on won't work after install on a 2.9.0 system:

```
{"error":"<p>Error Number: 1054<\/p>\n\n<p>Unknown column 'settings' in 'field list'<\/p>\n\n<p>SELECT `settings`\nFROM (`exp_modules`)\nWHERE `module_name` =  'Matrix_presets'<\/p>\n\n<p>Filename: third_party\/matrix_presets\/mcp.matrix_presets.php<\/p>\n\n<p>Line Number: 108<\/p>"}
```

**Comment by ignetic** [comment]
Thank you. Indeed I did find an issue with this. I have fixed this where I've added checks to see if this old settings field exists (v1.3). The addon now uses its own table so it should only access the old settings field when updating from an old version.
